kind = "web"
previewPath = "/"
title = "UMKM Digital"
version = "1.0.0"
id = "artifacts/umkm-digital"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20912

[services.development]
run = "pnpm --filter @workspace/umkm-digital run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/umkm-digital", "run", "build" ]
publicDir = "artifacts/umkm-digital/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20912"
BASE_PATH = "/"
